name: test Screenshot
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Add X11
        run: |
          brew install --cask xquartz
          sudo /opt/X11/libexec/privileged_startx || true
        working-directory: .
        
      - name: Start Xvfb
        run: |
            PATH=$PATH:/opt/X11/bin
            Xvfb :1 &
            export DISPLAY=:1

      - name: Take screenshot
        run: screencapture -C screenshot.png
      - uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
